data-aggregation/protected/controllers/UserController.php
<?php

class UserController extends DaController{
  public function accessRules(){
      return array(
          array('allow',
                'actions'=>array('login'),
                'users'=>array('*')),
          array('allow',  // allow all users to perform 'list' and 'show' actions
                'actions'=>array('index','view','logout','change'),
                'users'=>array('@') ),
          
          array('allow', // allow authenticated user to perform 'update' and 'delete' actions
                'actions'=>array('create', 'delete', 'update', 'reset'),
                'users'=>array('@'),
                'expression'=> '$user->isAdmin()',//$isOwnerOrAdmin,
          ),
          
          array('deny', 
                'users'=>array('*')),
      );
   }
  
  public function actionLogin(){
    
    if(!Yii::app()->user->isGuest){
      $this->redirect(Yii::app()->user->returnUrl);
    }
    $model = new LoginForm();
    if(isset($_POST["LoginForm"])){
      $model->setAttributes($_POST["LoginForm"]);
      if($model->validate() && $model->login()){
        $this->redirect(Yii::app()->user->returnUrl);
      }
    }
    $this->render( "login", array( "model" => $model) );
  }
  
  public function actionLogout(){
    Yii::app()->user->logout();
		$this->redirect("login");
  }

	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User'])){
			$model->setAttributes($_POST['User']);
			if($model->save()){
        Yii::app()->user->setFlash("success", "User has been created");
				$this->redirect(array('index'));
      }
      else{
        Yii::app()->user->setFlash("error", "Failed to create user");
      }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id){
		$model=$this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['User'])){
			$model->setAttributes($_POST['User']);
			if($model->save()){
        Yii::app()->user->setFlash("success","User has been updated successfully");
				$this->redirect(array('index'));
      }else
        Yii::app()->user->setFlash("error", "Failed to update user");
		}else{
      $model->password = "";
    }
		$this->render('update',array(
			'model'=>$model,
		));
	}
  
  public function actionReset(){
    $model = new ResetForm();
    $model->user_id = $_GET["id"];
    if(isset($_POST["ResetForm"])){
      $attributes = $_POST["ResetForm"];
      
      $model->setAttributes($attributes);
      
      if($model->validate()){
        $user = User::model()->findByPk($_POST["ResetForm"]["user_id"]);
        $user->setAttribute("password", $_POST["ResetForm"]["password"] );
        
        if($user->save()){
          Yii::app()->user->setFlash("success", "Password has been reset");
          $this->redirect($this->createUrl("user/index"));
        }
      }
    }
    $this->render("reset", array("model" => $model));
  }
  
  public function actionChange(){
    $model = new PasswordChangeForm();
    if(isset($_POST["PasswordChangeForm"])){
      $attributes = $_POST["PasswordChangeForm"];
      $currentUserId =  Yii::app()->user->id ;
      $attributes["user_id"] = $currentUserId;
      $model->setAttributes($attributes);
      
      if($model->validate()){
        $user = User::model()->findByPk($currentUserId);
        $user->password = $_POST["PasswordChangeForm"]["password"];
        $user->password_repeat = $_POST["PasswordChangeForm"]["password"];
        if($user->save()){
          Yii::app()->user->setFlash("success", "Password has been changed");
          $this->redirect("index");
        }
      }
    }
    $this->render("change", array("model" => $model));
  }

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id){
		if(1 || Yii::app()->request->isPostRequest){
			// we only allow deletion via POST request
			try{
        $this->loadModel($id)->delete();
        Yii::app()->user->setFlash("success", "User has been deleted");
      }
      catch(Exception $ex){
        Yii::app()->user->setFlash("error", "Failed to delete user");
      }
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
    $model = new User();
    $criteria = new CDbCriteria();
    $criteria->order = 't.id DESC, login ASC';
    $criteria->with = array("group") ;
    
    $itemCount = $model->count($criteria);
    $pages = new CPagination($itemCount);
    $pages->pageSize = DaConfig::PAGE_SIZE ;
    $pages->applyLimit($criteria);
    
    $users = $model->findAll($criteria);
		$this->render('index',array(
			'users'=>$users,
      'pages' => $pages  
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

data-aggregation/protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

data-aggregation/protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

data-aggregation/protected/views/layouts/default.php
<!DOCTYPE html>
<html >
  <head>
    <title><?php echo DaViewHelper::pageTitle($this->pageTitle); ?> </title>
    <?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
    <link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/form.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/login.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/jquery-ui-1.7.3.custom.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.fancybox-1.3.4.css" />
    
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/modernizr.custom.77819.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/custom.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.mousewheel-3.0.4.pack.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.fancybox-1.3.4.pack.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/jquery-ui-1.7.3.custom.min.js" ></script>
    
  </head>
  
  <body>
    <div id="main" class="width">
      <div class="head" > 
        <h1><a href="<?php echo $this->createUrl("/"); ?>" title="nchads" ><?php echo CHtml::image(Yii::app()->request->baseUrl."/images/nchads.jpg","NCHADs") ?> </a></h1>
      </div>
      <div class="breadcrumb" >
        <div style="float: left;" >
          <?php if(isset($this->breadcrumbs)):?>
            <?php $this->widget('zii.widgets.CBreadcrumbs', array('links'=>$this->breadcrumbs,)); ?>
          <?php endif?>
        </div>

        <div style="float:right;" >
          <?php if(!Yii::app()->user->isGuest) : ?>
          Welcome <b><?php echo Yii::app()->user->getName(); ?></b> <span class="item-separator"> | </span>
          <?php echo CHtml::link("Change Password", $this->createUrl("user/change"), array("class" => "btn-link") ) ?> 
          <span class="item-separator"> | </span>
          <?php echo CHtml::link("Logout", $this->createUrl("user/logout") , array("class" => "btn-link")) ?> 
          <?php endif; ?>
        </div>  
        <div style="clear:both;"></div>
      </div>
      <div> </div>
      <?php 
        $flashes = Yii::app()->user->getFlashes();
        if($flashes):
        foreach($flashes as $key => $value): ?>
        <div class=" round flash-<?php echo $key ?>" > <?php echo $value; ?> </div>
      <?php 
        endforeach;
        endif;
      ?>
      <?php echo $content; ?>
      <div class="clear" >&nbsp;</div>
      
    </div> 
    
    <footer  id="footer" class="width"> 
      <div >
          <div>
            <div style="float: right;color:#ccc; font-size: 0.8em;" >
              <?php echo Yii::app()->name; ?> version <?php echo Yii::app()->params["version"]; ?> </div>
          </div>  
          <div class="clear"> </div>
      </div> 
    </footer>  
    
    <div id="ajax_loading" class="loading round" >Waiting for server response</div>
    
    <script type="text/javascript">
      
      $(function(){
        $(".delete, .confirm").click(function(){

          var message = $(this).attr("data-tip") || "Are you sure to take this action";
          $(".flash-success, .flash-error").hide();

          if(!confirm(message)){
            return false;
          }
          show_loading();
          return true;
        });
          
        $("form").submit(function(){
          show_loading();
        });   
        
        $(".btn-save, .btn-action, .btn-action-edit, .btn-action-new, .btn-link, .breadcrumbs>a, .dashboard-title a").click(function(){
          show_loading();
        });
          
      });
  
    </script>
  </body>
</html>

data-aggregation/protected/views/layouts/error.php
<!DOCTYPE html>
<html >
  <head>
    <title><?php echo DaViewHelper::pageTitle($this->pageTitle); ?> </title>
    <?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/form.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/login.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/jquery-ui-1.7.3.custom.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.fancybox-1.3.4.css" />
    
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/modernizr.custom.77819.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/custom.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.mousewheel-3.0.4.pack.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/fancybox/jquery.fancybox-1.3.4.pack.js" ></script>
    <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl ?>/js/jquery-ui-1.7.3.custom.min.js" ></script>
    
  </head>
  
  <body>
    <div id="main" class="width">
      <div class="head" > 
        <h1><a href="<?php echo $this->createUrl("/"); ?>" title="nchads"  ><?php echo CHtml::image(Yii::app()->request->baseUrl."/images/nchads.jpg","NCHADs") ?> </a></h1>
      </div>
      <div> </div>
      
      <?php echo $content; ?>
    </div> 
    <div id="ajax_loading" class="loading round" >Waiting for server response</div>
  </body>
</html>

data-aggregation/protected/views/layouts/login.php
<!Doctype html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl ?>/css/login.css" />
    
  </head>
  
  <body>
    <div id="login" class="round" >
      <?php echo $content; ?>
    </div>
  </body>  
</html>

data-aggregation/protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>
  <?php if(!Yii::app()->user->isGuest): ?>  
    <span> <?php echo Yii::app()->user->getName(); ?> </span>
    <span> <?php echo Yii::app()->user->lastLoginAt; ?> </span>
  <?php endif; ?>  
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>